config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/booking_confirmation', to: 'pages#confirm'
  resources :bookings, only: [:index]
  get '/me', to: "users#index", as: :me
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :superheros do
     resources :bookings
     resource :favorite, only: [:create, :destroy]
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord  
  belongs_to :user
  belongs_to :superhero

  validates :date, presence: true
  validates :number_of_hours, presence: true
  validates :location, presence: true
  validates :event, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :superhero
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :superhero

  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: 0..5
  validates :description, presence: true
end

app/models/superhero.rb
class Superhero < ApplicationRecord
  belongs_to :user
  has_one_attached :img_url

  has_many :bookings
  has_many :favorites

  has_many :reviews, dependent: :destroy

  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?

  validates :name, presence: true
  validates :city, presence: true
  validates :superpower, presence: true
  validates :hourly_price, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :superheros, dependent: :destroy
  has_many :bookings 
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update]

  def index
    @bookings = Booking.where(user: current_user)
    @favorites = current_user.favorites
  end
  # 2.Create the show action

  def show
  end

  # 3.Create the new action
  def new
    @booking = Booking.new
  end

  # 4.Create the create action
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.superhero = Superhero.find(params[:superhero_id])
    if @booking.save!
      redirect_to booking_confirmation_path
    else
      render :new
    end
  end

  # 5.Create the edit action
  def edit
    @superhero = @booking.superhero
  end
  # 6.Create the update action

  def update
    @booking.update(booking_params)
    if @booking.save
      redirect_to superhero_bookings_path
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to superhero_bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date, :number_of_hours, :event, :location)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @favorite = Favorite.new
    @favorite.user = current_user
    @favorite.superhero = Superhero.find(params[:superhero_id])
    @favorite.save
  end

  def destroy
    @favorite = current_user.favorites.find_by(superhero_id: params[:superhero_id])
    @favorite.destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # dont forget to add :index
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def confirm

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
      @superhero = Superhero.find(params[:superhero_id])
      @review = Review.new
    end
    def create
      @review = Review.new(review_params)
      @superhero = Superhero.find(params[:superhero_id])
      @review.superhero = @superhero
      if @review.save
        redirect_to superhero_path(@superhero)
      else
        render :new
      end
    end
  
    private
  
    def review_params
      params.require(:review).permit(:rating, :description, :superhero_id)
    end
  end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  before_action :set_superhero, only: [:show, :edit, :update, :destroy]
#   Create the index action
def index
    if params[:query].present?
      sql_query = "city ILIKE :query OR name ILIKE :query"
      @superheros = Superhero.geocoded.where(sql_query, query: "%#{params[:query].downcase}%")
      @markers = @superheros.map do |superhero|
        {
          lat: superhero.latitude,
          lng: superhero.longitude
        }
      end
    else
      @superheros = Superhero.geocoded
      @markers = @superheros.map do |superhero|
        {
          lat: superhero.latitude,
          lng: superhero.longitude
        }
      end
    end
end
# 2.Create the show action
def show
  @booking = Booking.new
end
# 3.Create the new action
def new
  @superhero = Superhero.new
end
# 4.Create the create action
def create
  @superhero = Superhero.new(superhero_params)
  @superhero.user = current_user
  if @superhero.save!
    redirect_to superhero_path(@superhero)
  else
    render :new
  end
end
# 5.Create the edit action
def edit
end
# 6.Create the update action

def update
  @superhero.update(superhero_params)
  if @superhero.save
    redirect_to superhero_path(@superhero)
  else
    render :edit
  end
end

def destroy
  @superhero.destroy
  redirect_to me_path
end

private

def set_superhero
  @superhero = Superhero.find(params[:id])
end

def superhero_params
  params.require(:superhero).permit(:name, :city, :superpower, :hourly_price, :img_url, :description)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @superheros = Superhero.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_edit_booking.html.erb
<%= simple_form_for [@superhero, @booking] do |f| %>
    <div class="form-group">
      <div class="field">
        <%= f.input :date, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :number_of_hours, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :event, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :location, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.button :submit, class: "btn dark-blue-btn-outline btn-block" %>
      </div>
    </div>
<% end %>

app/views/bookings/edit.html.erb
<h3 class="mb-3"> Edit your booking </h3>

<div class="col-lg-15">
    <div class="checkout-column mb-5">

      <div class="edit-card">
        <div class="booking-details mb-3">
        </div>
        <div class="booking-form">
          <%= render "edit_booking" %> 
        </div>
      </div>
        </div>
      </div>
    </div>
  </div>

app/views/bookings/index.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="active"><a data-toggle="tab" href="#bookings" class="btn dark-blue-btn">My Bookings</a></li>
  <li><a data-toggle="tab" href="#favorites" class="btn dark-blue-btn-outline">My Favorites</a></li>
</ul>

<div class="tab-content">
  <div id="bookings" class="tab-pane fade in active">
    <h1 class="super-text"> My Bookings</h1>
    <div class="row">
       <div class="col">
        <div class="grid booked-grid mb-5">
          <% current_user.bookings.each do |booking| %>
           <div class="booked-superhero details-card d-flex flex-column mt-5 mb-0">
             <div class="superhero-booked-info">
                <div class="flexbox booking-details flex-column align-right mb-1">
                  <div class="booking-info"><span><strong>Date:</strong> <%= booking.date.strftime('%B, %d, %Y') %></span></div>
                  <div class="booking-info"><span><strong>Event:</strong> <%= booking.event %></span></div>
                  <div class="booking-info"><span><strong>Location:</strong> <%= booking.location %></span></div>
                </div>
                <hr width="67%" align="left">
                 <div><h1 class="super-text mt-2" style="font-size: 18px"><%= booking.superhero.name %></h1></div>
             </div>
             <%= cl_image_tag booking.superhero.img_url.key, crop: :thumb, gravity: :face, class: "super-hero-booking-picture mr-4" %>
             <div class="edit-delete-cancel-btn mt-3">
              <%= link_to 'Edit', edit_superhero_booking_path(booking.superhero, booking), class: "change-btn"%>
              <%= link_to "Cancel",
               superhero_booking_path(booking.superhero, booking),
               method: :delete,
               data: { confirm: 'Are you sure you want to cancel?'},
               class: "change-btn" %>
             </div>
           </div>

         <%end%>
        </div>
       </div>
    </div>
  </div>
  <div id="favorites" class="tab-pane fade">
  <h1 class="super-text"> My Favorites</h1>
    <div class="superhero-grid mb-5">
<% @favorites.each do |favorite| %>
<div class="index-card">
  <div>
    <div class="index-card-image-box">
    <%# add a conditional to check if image exists below, else display placeholder %>
    <% if favorite.superhero.img_url.attached? %>
      <%= cl_image_tag favorite.superhero.img_url.key, class: "index-card-image" %>
      <% else %>
      <%= image_tag "questionmark.jpg", class: "index-card-image" %>
      <% end %>
      <div class="price-chip">
        <h3 class="superhero-price">$<%= favorite.superhero.hourly_price %>/hr</h3>
      </div>
    </div>
  <div class="superhero-details">
    <div class="superhero-attributes">
      <h2 class="superhero-name"> <%= favorite.superhero.name %> </h2>
      <h4 class="superhero-powers"><em><strong>Power: </strong> <%= favorite.superhero.superpower %></em></h4>
      <h4 class="superhero-powers"><em><strong>City: </strong> <%= favorite.superhero.city %></em></h4>
    </div>
  </div>
  </div>
  <%= link_to "Book #{favorite.superhero.name}", superhero_path(favorite.superhero), class: "btn book-card-button dark-blue-btn-card btn-block"%>
</div>
<% end %>
</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSuperheroForRent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&family=Russo+One&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://polyfill.io/v3/polyfill.min.js?features=default">
      </script>
    <div class="footer mt-5 d-flex justify-content-between fixed-bottom">
      <p class="footer-text">Made with ♥️ at LeWagon Mexico</p>
      <span><a href="#"><i class="fab fa-instagram"></i></a>
       <a href="#"><i class="fab fa-facebook"></i></a>
       <a href="#"><i class="fab fa-twitter"></i></a></span>
    </div>
  </body>
</html>

app/views/pages/confirm.html.erb
<h2 class="mb-3">Your booking is confirmed</h1>

<%= link_to 'See my bookings', bookings_path, class: "btn dark-blue-btn-outline" %>

app/views/pages/home.html.erb
<div class="home">
  
    <%= image_tag "flying.png", style: 'height: 76vh', class: "bg-image" %>
  
  

<div class="site-header">
  <h1 class="site-title">MYSUPER</h1>
  <h3 class="site-subtitle mb-5"><strong>Stay safe out there... with a <span>SUPER</span> bodyguard</strong></h3>
    <%# create a dropdown with list of cities available for above input %>
    <%# <input class="form-control mr-sm-2 home-search" type="search" placeholder="Enter Date" aria-label="Search"> %>
    <%# create a calendar where you can select one date for above input %
   <%= form_tag superheros_path, method: :get do %>
  <div>
    <%= form_tag superheros_path, class: "form-inline", method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control search-input mr-1 radius-1px",
      placeholder: "City or Superhero Name"
    %>
    <%= submit_tag "Search", class: "btn home-search-btn mr-2"  %>
    <% end %>
   </div>

</div>
</div>

app/views/reviews/_form.html.erb
 <%= simple_form_for [ @superhero, @review ] do |f| %>
    <div class="form-group">
      <div class="field">
        <%= f.input :rating, as: :radio_buttons, collection: [ 1, 2, 3, 4, 5], wrapper: :vertical_collection_inline, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :description, input_html: { maxlength: 150 }, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.button :submit, class: "btn dark-blue-btn-outline" %>
      </div>
    </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="container">
  <h2>Edit your review!</h2>
  <%= render "form" %>
  <%= link_to "Go back to #{@superhero.name}", superheros_path %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h2>Create a new review for <%= @superhero.name %>!</h2>
  <%= render "form" %>
  <%= link_to "Go back to #{@superhero.name}", superhero_path(@superhero), class: "btn dark-rd-btn" %>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form_booking.html.erb
<%= simple_form_for [@superhero, @booking] do |f| %>
    <div class="form-group">
      <div class="field">
        <%= f.input :date, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :number_of_hours, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :event, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :location, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.button :submit, class: "btn dark-rd-btn btn-block" %>
      </div>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to "MYSUPER", root_path, class: "navbar-brand super-text", style: "color: #d90429" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "All Superguards", superheros_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", superhero_bookings_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Listings", me_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <i class="fas fa-user-circle avatar dropdown-toggle ml-3 fa-lg mb-1" id="navbarDropdown" data-toggle="dropdown" aria-haspopup='true' aria-expanded='false'></i>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Create Superhero", new_superhero_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/superheros/_form.html.erb
 <%= simple_form_for(@superhero) do |f| %>
    <div class="form-group">
      <div class="field">
        <%= f.input :name, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :city, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :description, class: "form-control", as: :text, :input_html => { class: 'test', :cols => 5, :rows => 6 } %>
      </div>
      <div class="field">
        <%= f.input :superpower, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :hourly_price, class: "form-control" %>
      </div>
      <div class="field"> 
        <%= f.input :img_url, as: :file, class: "form-control"%>
      </div>
      <div class="field">
        <%= f.button :submit, class: "btn btn-block dark-blue-btn" %>
      </div>
    </div>
<% end %>

app/views/superheros/_form_booking.html.erb
<%= simple_form_for(@booking) do |f| %>
    <div class="form-group">
      <div class="field">
        <%= f.input :date, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :number_of_hours, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :event, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.input :location, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.button :submit, class: "btn btn-info" %>
      </div>
    </div>
<% end %>

app/views/superheros/edit.html.erb
<div class="container mb-5">
  <h2>Edit your superhero!</h2>
  <%= render "form" %>
  <%= link_to "Go back to superheros", superheros_path, class: "btn dark-blue-btn-outline btn-block" %>
</div>

app/views/superheros/index.html.erb
<div class="index-heading mb-5">
  <h4 class="search-params">
  <%= @superheros.count %> superheroes
  </h4>
  <h1 class="location-params">
  Superguards in Your Area
  </h1>
  <div>
    <%= form_tag superheros_path, class: "form-inline", method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control mr-1",
      placeholder: "City or Superhero Name"
    %>
    <%= submit_tag "Search", class: "btn dark-blue-btn-outline mr-2"  %>
    <% end %>
   </div>
</div>

<div class="row">
<div class="col-lg-8 border-right">
  <div class="superhero-grid mb-5">
<% @superheros.each do |superhero| %>
<div class="index-card">
  <div>
    <div class="index-card-image-box">
    <%# add a conditional to check if image exists below, else display placeholder %>
    <% if superhero.img_url.attached? %>
      <%= cl_image_tag superhero.img_url.key, class: "index-card-image" %>
      <% else %>
      <%= image_tag "questionmark.jpg", class: "index-card-image" %>
      <% end %>
      <div class="price-chip">
        <h3 class="superhero-price">$<%= superhero.hourly_price %>/hr</h3>
      </div>
    </div>
  <div class="superhero-details">
    <div class="superhero-attributes">
      <h2 class="superhero-name"> <%= superhero.name %> </h2>
      <h4 class="superhero-powers"><em><strong>Power: </strong> <%= superhero.superpower %></em></h4>
      <h4 class="superhero-powers"><em><strong>City: </strong> <%= superhero.city %></em></h4>
    </div>
  </div>
  </div>
  <%= link_to "Book #{superhero.name}", superhero_path(superhero), class: "btn book-card-button dark-blue-btn-card btn-block"%>
</div>
<% end %>
</div>
</div>
<div class="col-lg-4" style="position: sticky">
  <div id="map" data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" class="ml-2"></div>
</div>
</div>

app/views/superheros/new.html.erb
<div class="container mb-5">
  <h2>Create a new superhero!</h2>
  <%= render "form" %>
  <%= link_to "Go back to superheros", superheros_path, class: "btn dark-blue-btn-outline btn-block" %>
</div>

app/views/superheros/show.html.erb
<div class="index-heading mb-3">
  <h1 class="huge-name">
    <%= @superhero.name %>
  </h1>
</div>

<div class="show-superhero">
  <div class="super-and-reviews">
    <div class="superhero-details-card mb-5">
    <% if @superhero.img_url.attached? %>
      <%= cl_image_tag @superhero.img_url.key, crop: :thumb, gravity: :face, class: "super-hero-picture mr-4" %>
      <% else %>
      <%= image_tag "questionmark.jpg", class: "super-hero-picture mr-4" %>
      <% end %>
      <div class="superhero-info">
        <div class="flexbox d-flex mb-3">
          <div><i class="far fa-star"> <%= @superhero.reviews.length > 0 ? (@superhero.reviews.average(:rating)).round(2) : 5.00 %></i></div>
          <div class="hero-city ml-3"><span><%= @superhero.city %></span></div>
        </div>
        <h4 class="">Superpower: <%= @superhero.superpower %></h2>
        <p><%= @superhero.description %></p>
        <div>
        <%= link_to "Add to Favorites", superhero_favorite_path(@superhero), method: :post, class: "btn dark-blue-btn" %>
        <%= link_to "Remove from Favorites", superhero_favorite_path(@superhero), method: :delete, class: "btn dark-blue-btn-outline" %>
        </div>
      </div>
    </div>
    <div class="reviews-show mb-5">
      <div class="reviews-header mb-3">
        <h1 class="mr-3">Reviews</h1>
        <div>
          <%= link_to "New Review", new_superhero_review_path(@superhero), class: "btn dark-blue-btn-outline" %>
        </div>
      </div>
      <div class="reviews-display mb-3">
        <%  if @superhero.reviews.blank? %> 
        <%= @superhero.name %> has no reviews!
        <% else %>
        <% @superhero.reviews.each do |review| %>
          <div class="review-card mb-3">
            <div class="mb-1">
              <% review.rating.times do %>
            <span>⚡︎</span>
            <% end %>
            </div>
            <p><%= review.description %></p>
          </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="checkout-column mb-5">
    <div class="booking-card ml-5">
      <div class="booking-details mb-3">
        <span><strong>$<%= @superhero.hourly_price %></strong>/hour</span>
        <i class="far fa-star"><%= @superhero.reviews.length > 0 ? (@superhero.reviews.average(:rating)).round(2) : 5.00 %></i>
      </div>
      <div class="booking-form">
        <%= render "shared/form_booking" %> 
      </div>
    </div>
      </div>
    </div>
  </div>
  

</div>



</div>

app/views/users/index.html.erb
<h1 class="super-text mb-5">My Superguard Listings</h1>
<div class="mb-5">
  <div class="grid listings-grid mb-5">
          <% @superheros.each do |superhero| %>
           <div class="index-card">
  <div>
    <div class="index-card-image-box">
    <%# add a conditional to check if image exists below, else display placeholder %>
    <% if superhero.img_url.attached? %>
      <div class="index-card-image" style="background-image: url('<%= cl_image_path(superhero.img_url.key) %>')">
      </div>
      <% else %>
      <%= image_tag "questionmark.jpg", class: "index-card-image", crop: :thumb, gravity: :face %>
      <% end %>
      <div class="price-chip">
        <h3 class="superhero-price">$<%= superhero.hourly_price %>/hr</h3>
      </div>
    </div>
  <div class="superhero-details">
    <div class="superhero-attributes">
      <h2 class="superhero-name"> <%= superhero.name %> </h2> 
      <h4 class="superhero-powers"><em><strong>Power: </strong> <%= superhero.superpower %></em></h4>
      <h4 class="superhero-powers"><em><strong>City: </strong> <%= superhero.city %></em></h4>
    </div>
  </div>
  </div>
  <%= link_to "Edit Superhero", edit_superhero_path(superhero), class: "badge badge-pill" %>
  <%= link_to "Unlist Superhero", superhero_path(superhero),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "badge badge-pill" %>
  <%= link_to "View Superhero Profile", superhero_path(superhero), class: "badge badge-pill" %>
</div>
         <%end%>
        </div>
        <%= link_to "Create Superhero", new_superhero_path, class: "btn dark-blue-btn-outline mr-1" %>

</div>
 